---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker Image from Hub
      shell: /usr/local/bin/docker pull deeksha2008/scientific-calculator:latest

    - name: Stop old container
      shell: /usr/local/bin/docker stop scientific-calc-app || true
      
    - name: Remove old container
      shell: /usr/local/bin/docker rm scientific-calc-app || true
     
    - name: Running container
      shell: /usr/local/bin/docker run -d --name scientific-calc-app -p 8081:8080 deeksha2008/scientific-calculator:latest

