---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  tasks:
    - name: Pull Docker Image from Hub
      shell: /usr/local/bin/docker pull deeksha2008/scientific-calculator:latest

    - name: Stop and Remove old container
      shell: /usr/local/bin/docker rm -f scientific-calc-app || true
     
    - name: Run new container
      shell: /usr/local/bin/docker run -d -it --name scientific-calc-app -p 8081:8080 deeksha2008/scientific-calculator:latest
